# Generated by Django 5.0.1 on 2024-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
